services:
  mysql-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: online_shop
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  laravel-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - mysql-db
    networks:
      - app-network

  nginx-webserver:
    image: nginx:1.27-alpine
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel-app
    networks:
      - app-network

  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile.next
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql-db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql-db
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge